// E2E screenshot capture + persisted manifest.
//
// Usage inside a testWidgets() call:
//   final et = E2ETester(tester);
//   await et.init('test name');           // captures '00_initial'
//   await et.tap(...);                    // auto-screenshot per action
//   await et.screenshot('result');        // manual checkpoint
//   await et.pass();   // or et.fail()    // record final status
//
// Output is written to:
//   build/e2e_report/screenshots/*.png   ← captured frames
//   build/e2e_report/manifest.json       ← step labels + status, consumed by
//                                          tool/e2e_dashboard.dart
//
// The unified dashboard at build/e2e_dashboard/index.html is generated by
// `dart run tool/e2e_dashboard.dart` (called automatically by the e2e make
// targets). The dashboard reads this manifest to render every step's
// screenshot inline with a lightbox viewer.
//
// The manifest is rewritten after every captured screenshot so partial state
// is preserved even if later tests crash. Screenshots from previous runs of
// the SAME test are cleared on `et.init()`; results from OTHER tests are
// preserved so partial reruns don't wipe the dashboard.

import 'dart:convert';
import 'dart:io';
import 'dart:ui' as ui;

import 'package:cb_file_manager/e2e/cb_e2e_config.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:path/path.dart' as p;

import 'e2e_keys.dart' as keys;
import 'e2e_sandbox_paths.dart';

// ---------------------------------------------------------------------------
// Internal state
// ---------------------------------------------------------------------------

class _Entry {
  final String testName;
  final String step;
  final String filename;
  final DateTime ts;
  _Entry({
    required this.testName,
    required this.step,
    required this.filename,
    required this.ts,
  });
}

/// Upper bound for every settle performed by this reporter.
///
/// `pumpAndSettle` defaults to a ten minute timeout. A screen that never stops
/// animating — a video thumbnail placeholder still waiting on its decoder, for
/// example — therefore blocks a capture run for ten minutes per frame before
/// the surrounding try/catch can fall back to a plain pump. Capturing a
/// still-loading frame is always preferable to losing the run.
const Duration kE2ESettleTimeout = Duration(seconds: 12);

final List<_Entry> _log = [];
Directory? _reportDir;
Directory? _screenshotsDir;
int _counter = 0;
bool _manifestLoaded = false;

/// Tests cleared during the current process run. We only clear a test's
/// previous screenshots once per process — on the first `init()` call —
/// so multiple `screenshot()` calls within the same test don't wipe each
/// other out.
final Set<String> _clearedThisRun = {};

/// Stores test results so the HTML report can show pass/fail badges.
/// Key = test name, Value = true (passed) / false (failed).
final Map<String, bool> _testResults = {};

/// Records the result of a test for the HTML report.
///
/// Call this at the end of each `testWidgets()` test:
///   await recordTestResult('my test', true);   // passed
///   await recordTestResult('my test', false);  // failed
///
/// If not called, the test shows with no badge (unknown status).
void recordTestResult(String testName, bool passed) {
  _testResults[testName] = passed;
  _writeResultsJson(); // persist so e2e_parallel can read it after merge
  _saveManifest();
}

/// Exports _testResults to build/e2e_report/results.json so e2e_parallel
/// Writes `results.json` with the bool pass/fail map. Kept as a side artifact
/// for tooling that still grep's for it (e.g. external CI dashboards). The
/// authoritative data store is `manifest.json`.
Future<void> _writeResultsJson() async {
  if (_reportDir == null) return;
  try {
    final file = File(p.join(_reportDir!.path, 'results.json'));
    final entries = _testResults.entries
        .map((e) => '  "${_esc(e.key)}": ${e.value}')
        .join(',\n');
    await file.writeAsString('{\n$entries\n}');
  } catch (_) {}
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Captures a screenshot, saves it as a PNG, and updates the HTML report.
///
/// [testName] must match the string passed to [testWidgets].
/// [step] is a human-readable label, e.g. `'initial state'` or `'result'`.
///
/// Non-fatal: all errors are caught so a failing screenshot never causes a
/// test to fail.
Future<void> captureE2EScreenshot(
  WidgetTester tester,
  String testName,
  String step,
) async {
  try {
    await _ensureReportDir();

    // Let the UI fully settle before grabbing a frame.
    // The action that triggered this screenshot already called pumpAndSettle,
    // so this is mostly free (returns immediately when already settled).
    try {
      await tester.pumpAndSettle(
        kCbE2EFast
            ? const Duration(milliseconds: 100)
            : const Duration(seconds: 1),
        EnginePhase.sendSemanticsUpdate,
        kE2ESettleTimeout,
      );
    } catch (_) {
      await tester.pump(
        kCbE2EFast
            ? const Duration(milliseconds: 50)
            : const Duration(milliseconds: 200),
      );
    }
    await tester.pump(
      kCbE2EFast
          ? const Duration(milliseconds: 16)
          : const Duration(milliseconds: 50),
    );

    final index = ++_counter;
    final slug =
        '${index.toString().padLeft(3, '0')}_${_slugify(testName)}_${_slugify(step)}';

    final Uint8List? bytes = await _capturePngBytes(tester, slug);

    if (bytes != null && bytes.isNotEmpty) {
      final filename = '$slug.png';
      final file = File(p.join(_screenshotsDir!.path, filename));
      await file.writeAsBytes(bytes);

      _log.add(
        _Entry(
          testName: testName,
          step: step,
          filename: filename,
          ts: DateTime.now(),
        ),
      );

      // Persist manifest every 5 screenshots so a crash mid-run still leaves
      // a usable artifact behind. Cheap relative to the screenshot capture
      // itself.
      if (_counter % 5 == 0) await _saveManifest();

      if (kDebugMode) {
        debugPrint(
          '[E2E Report] Screenshot saved: $filename  →  ${_screenshotsDir!.path}',
        );
      }
    } else {
      if (kDebugMode) {
        debugPrint(
          '[E2E Report] No bytes captured for "$slug" — screenshot skipped',
        );
      }
    }
  } catch (e, st) {
    if (kDebugMode) {
      debugPrint(
        '[E2E Report] captureE2EScreenshot failed (non-fatal): $e\n$st',
      );
    }
  }
}

// ---------------------------------------------------------------------------
// E2ETester — WidgetTester wrapper that auto-screenshots every interaction
// ---------------------------------------------------------------------------

/// WidgetTester wrapper with optional action-by-action screenshots.
///
/// Usage:
/// ```dart
/// testWidgets('my test', (WidgetTester tester) async {
///   final et = E2ETester(tester);
///   await et.init('my test');
///
///   // Interactions settle the UI; full screenshot mode also captures each one.
///   await et.enterText(finder, 'hello');
///   await et.tap(finder);
///   await et.longPress(finder);
///   await et.drag(finder, const Offset(0, -100));
///   await et.scrollUntilVisible(finder, scrollable, 100);
///   await et.pumpAndSettle();
///   await et.screenshot('custom label');       // manual snapshot any time
/// });
/// ```
///
/// Methods return `Future<void>` to match [WidgetTester] signatures.
/// Finder errors (zero elements) are logged and skip without failing the test.
class E2ETester {
  /// The wrapped tester. Exposed for helpers that still need the raw
  /// [WidgetTester] (e.g. some `page.go()` extensions).
  final WidgetTester tester;

  /// Base label prepended to every auto-generated screenshot step name.
  /// Set via [init].
  String _label = '';

  E2ETester(this.tester);

  /// Initialise the test label and capture the first "initial state" screenshot.
  /// Call once at the top of each test, before any interactions:
  ///   await et.init('my test');
  Future<void> init(String label) async {
    _label = label;
    await _ensureReportDir();
    // Drop any stale screenshots from a previous run of this same test so
    // reruns of a subset of tests don't show a mixed history. Other tests'
    // entries stay intact.
    await _clearTestEntries(label);
    await captureE2EScreenshot(tester, _label, '00_initial');
  }

  // -------------------------------------------------------------------------
  // Generic / manual screenshot helpers
  // -------------------------------------------------------------------------

  /// Manually capture a screenshot with a custom [step] label.
  /// Always flushes the manifest to disk (useful at test end).
  Future<void> screenshot(String step) async {
    await captureE2EScreenshot(tester, _label, step);
    await _saveManifest(); // always flush at explicit checkpoints
  }

  /// Wait for animations to settle, then capture a screenshot.
  Future<void> screenshotSettled(String step) async {
    try {
      await tester.pumpAndSettle(const Duration(seconds: 2));
    } catch (_) {
      await tester.pump(const Duration(milliseconds: 500));
    }
    await tester.pump(const Duration(milliseconds: 200));
    await captureE2EScreenshot(tester, _label, step);
  }

  /// Capture a screenshot, then run [expectation], then capture again.
  /// Useful for documenting assertion states without duplicating the assertion.
  Future<void> screenshotBeforeExpect(
    String step,
    Future<void> Function() expectation,
  ) async {
    await captureE2EScreenshot(tester, _label, step);
    await expectation();
  }

  /// Run [expectation], then capture a screenshot.
  /// Useful for documenting the result of a series of steps.
  Future<void> screenshotAfterExpect(
    String step,
    Future<void> Function() expectation,
  ) async {
    await expectation();
    await captureE2EScreenshot(tester, _label, step);
  }

  /// Record that this test passed. Call at the end of the test.
  /// Flushes the manifest immediately.
  Future<void> pass() async {
    recordTestResult(_label, true);
    await _saveManifest();
  }

  /// Record that this test failed. Call at the end of the test.
  /// Flushes the manifest immediately.
  Future<void> fail() async {
    recordTestResult(_label, false);
    await _saveManifest();
  }

  // -------------------------------------------------------------------------
  // Internal sequencing
  // -------------------------------------------------------------------------

  int _actionCounter = 0;

  String _seq(String action, [String? detail]) {
    final c = (++_actionCounter).toString().padLeft(3, '0');
    return detail != null ? '${action}_${c}_$detail' : '${action}_$c';
  }

  /// Runs [fn] then captures a screenshot.  Never throws.
  Future<void> _act(
    String action,
    Future<void> Function() fn, [
    String? detail,
  ]) async {
    await fn();
    if (kCbE2EFullScreenshots) {
      await captureE2EScreenshot(tester, _label, _seq(action, detail));
    } else {
      await _settleAfterAction();
    }
  }

  Future<void> _settleAfterAction() async {
    try {
      await tester.pumpAndSettle(
        const Duration(milliseconds: 100),
        EnginePhase.sendSemanticsUpdate,
        kE2ESettleTimeout,
      );
    } catch (_) {
      await tester.pump(const Duration(milliseconds: 50));
    }
  }

  // -------------------------------------------------------------------------
  // Widget interaction forwards (each auto-screenshots after running)
  // -------------------------------------------------------------------------

  /// See [WidgetTester.tap].
  Future<void> tap(Finder finder, {String? detail}) =>
      _act('tap', () async => await tester.tap(finder), detail);

  /// See [WidgetTester.longPress].
  Future<void> longPress(Finder finder, {String? detail}) =>
      _act('long_press', () async => await tester.longPress(finder), detail);

  /// See [WidgetTester.enterText].
  Future<void> enterText(Finder finder, String text, {String? detail}) => _act(
    'enter_text',
    () async => await tester.enterText(finder, text),
    detail ?? text,
  );

  /// See [WidgetTester.drag].
  Future<void> drag(Finder finder, Offset offset, {String? detail}) =>
      _act('drag', () async => await tester.drag(finder, offset), detail);

  /// See [WidgetTester.fling].
  Future<void> fling(Finder finder, Offset offset, {String? detail}) => _act(
    'fling',
    () async => await tester.fling(finder, offset, 3000),
    detail,
  );

  /// Scrolls [scrollable] by [distance] until [target] is visible.
  /// Signature matches Flutter SDK 2.x: scrollUntilVisible(scrollable, distance).
  /// If [target] is provided the method first calls ensureVisible on it.
  Future<void> scrollUntilVisible(
    Finder target,
    Finder scrollable,
    double distance, {
    String? detail,
  }) => _act('scroll', () async {
    await tester.ensureVisible(target);
    await tester.scrollUntilVisible(scrollable, distance);
  }, detail);

  /// See [WidgetTester.ensureVisible].
  Future<void> ensureVisible(Finder finder) async {
    await tester.ensureVisible(finder);
  }

  /// See [WidgetTester.pump].
  Future<void> pump([Duration? duration]) async {
    await tester.pump(duration);
  }

  /// Pump until animations are done.
  /// [pumpAndSettle] does NOT auto-screenshot — it is a timing wait, not a
  /// user-visible action. Use [screenshotSettled] when you also need a frame.
  Future<void> pumpAndSettle([Duration? duration]) async {
    try {
      await tester.pumpAndSettle(
        duration ?? const Duration(milliseconds: 100),
        EnginePhase.sendSemanticsUpdate,
        kE2ESettleTimeout,
      );
    } catch (_) {
      await tester.pump(const Duration(milliseconds: 100));
    }
  }

  // -------------------------------------------------------------------------
  // Keyboard helpers — sendKeyDownEvent / sendKeyUpEvent / sendKeyEvent
  // These don't use _act because WidgetTester key methods don't take a callback.
  // -------------------------------------------------------------------------

  /// Press [key] down.
  Future<void> keyDown(LogicalKeyboardKey key) async {
    await tester.sendKeyDownEvent(key);
    if (kCbE2EFullScreenshots) {
      await captureE2EScreenshot(tester, _label, 'key_down_${key.keyLabel}');
    } else {
      await _settleAfterAction();
    }
  }

  /// Release [key].
  Future<void> keyUp(LogicalKeyboardKey key) async {
    await tester.sendKeyUpEvent(key);
    if (kCbE2EFullScreenshots) {
      await captureE2EScreenshot(tester, _label, 'key_up_${key.keyLabel}');
    } else {
      await _settleAfterAction();
    }
  }

  /// Full key press: down → up → screenshot.
  Future<void> keyPress(LogicalKeyboardKey key) async {
    await tester.sendKeyDownEvent(key);
    await tester.sendKeyUpEvent(key);
    if (kCbE2EFullScreenshots) {
      await captureE2EScreenshot(tester, _label, 'key_press_${key.keyLabel}');
    } else {
      await _settleAfterAction();
    }
  }

  // -------------------------------------------------------------------------
  // Shortcut helpers — common Finder + action combos
  // -------------------------------------------------------------------------

  /// Finder.byIcon + tap.
  Future<void> tapIcon(IconData icon, {String? detail}) =>
      tap(find.byIcon(icon), detail: detail ?? 'icon_${icon.codePoint}');

  /// Finder.byType + tap.
  Future<void> tapByType(Type type, {String? detail}) =>
      tap(find.byType(type), detail: detail ?? type.toString());

  /// Finder.byKey + tap.
  Future<void> tapByKey(ValueKey key, {String? detail}) =>
      tap(find.byKey(key), detail: detail ?? key.toString());

  /// Finder.byIcon + longPress.
  Future<void> longPressIcon(IconData icon, {String? detail}) =>
      longPress(find.byIcon(icon), detail: detail ?? 'icon_${icon.codePoint}');

  /// Finder.byType + longPress.
  Future<void> longPressByType(Type type, {String? detail}) =>
      longPress(find.byType(type), detail: detail ?? type.toString());

  /// Finder.byType + enterText.
  Future<void> enterTextByType(Type type, String text, {String? detail}) =>
      enterText(find.byType(type), text, detail: detail ?? type.toString());

  // -------------------------------------------------------------------------
  // Project-specific helper wrappers (auto-screenshot after each action)
  // -------------------------------------------------------------------------

  /// Single-tap a file row (grid or list). Auto-screenshots after.
  Future<void> tapFileRow(String path, {String? detail}) => _act(
    'tap_file',
    () => keys.tapFileRow(tester, path),
    detail ?? _lastName(path),
  );

  /// Double-tap a folder row to navigate into it. Auto-screenshots after.
  Future<void> tapFolderRow(String path, {String? detail}) => _act(
    'tap_folder',
    () => keys.tapFolderRow(tester, path),
    detail ?? _lastName(path),
  );

  /// Single-tap a folder row to select it (no navigation). Auto-screenshots after.
  Future<void> selectFolderRow(String path, {String? detail}) => _act(
    'select_folder',
    () => keys.selectFolderRow(tester, path),
    detail ?? _lastName(path),
  );

  /// Ctrl+click to add a file to the multi-selection. Auto-screenshots after.
  Future<void> selectFileWithCtrl(String path, {String? detail}) => _act(
    'ctrl_select',
    () => keys.selectFileWithCtrl(tester, path),
    detail ?? _lastName(path),
  );

  /// Right-click a file row to open its context menu. Auto-screenshots after.
  Future<void> rightClickFileRow(String path, {String? detail}) => _act(
    'right_click_file',
    () => keys.rightClickFileRow(tester, path),
    detail ?? _lastName(path),
  );

  /// Right-click a folder row to open its context menu. Auto-screenshots after.
  Future<void> rightClickFolderRow(String path, {String? detail}) => _act(
    'right_click_folder',
    () => keys.rightClickFolderRow(tester, path),
    detail ?? _lastName(path),
  );

  /// Tap a context menu item by its action id. Auto-screenshots after.
  Future<void> tapContextMenuItem(String actionId, {String? detail}) => _act(
    'menu',
    () => keys.tapContextMenuItem(tester, actionId),
    detail ?? actionId,
  );

  /// Right-click on the background (empty area) to open the background context menu.
  /// Auto-screenshots after.
  Future<void> openBackgroundContextMenu({
    Offset? tapPosition,
    String? detail,
  }) => _act(
    'bg_menu',
    () => keys.openBackgroundContextMenu(tester, tapPosition: tapPosition),
    detail,
  );

  /// Send a keyboard shortcut (modifiers + key). Auto-screenshots after.
  Future<void> sendKeyboardShortcut({
    LogicalKeyboardKey key = LogicalKeyboardKey.keyC,
    bool ctrl = false,
    bool shift = false,
    bool alt = false,
    String? detail,
  }) => _act(
    'shortcut',
    () => keys.sendKeyboardShortcut(
      tester,
      key: key,
      ctrl: ctrl,
      shift: shift,
      alt: alt,
    ),
    detail,
  );

  /// Type text into the currently focused TextField. Auto-screenshots after.
  Future<void> typeIntoFocusedField(String text, {String? detail}) => _act(
    'type',
    () => keys.typeIntoFocusedField(tester, text),
    detail ?? text,
  );

  /// Tap the dialog confirm button. Auto-screenshots after.
  Future<void> tapDialogConfirm({String? buttonText, String? detail}) => _act(
    'confirm',
    () => keys.tapDialogConfirm(tester, buttonText: buttonText),
    detail ?? buttonText ?? 'confirm',
  );

  /// Returns the last path segment — used as a concise screenshot label.
  static String _lastName(String path) {
    final sep = path.contains('/') ? '/' : r'\';
    return path.split(sep).lastWhere((s) => s.isNotEmpty, orElse: () => path);
  }
}

// ---------------------------------------------------------------------------
// Screenshot capture with two-layer fallback
// ---------------------------------------------------------------------------

/// Returns raw PNG bytes or null if all capture methods fail.
///
/// Layer 1 — [IntegrationTestWidgetsFlutterBinding.takeScreenshot]:
///   Uses the native `captureScreenshot` method channel. Works when running
///   with `flutter test` on devices that support it (Android, iOS, some
///   desktop configurations). May throw [MissingPluginException] on Windows
///   desktop when no driver is connected.
///
/// Layer 2 — [WidgetTester.captureImage] via [RenderRepaintBoundary.toImage]:
///   Pure-Dart fallback that walks the render tree. Works on all platforms
///   including Windows desktop `flutter test`.
Future<Uint8List?> _capturePngBytes(WidgetTester tester, String slug) async {
  // --- Layer 1: integration_test channel ---
  try {
    final binding = IntegrationTestWidgetsFlutterBinding.instance;
    final List<int> bytes = await binding.takeScreenshot(slug);
    if (bytes.isNotEmpty) {
      return Uint8List.fromList(bytes);
    }
  } catch (_) {
    // MissingPluginException or StateError on desktop — fall through.
  }

  // --- Layer 2: direct render-tree capture via flutter_test's captureImage ---
  // captureImage(Element) is a top-level function exported by flutter_test.
  // It walks up to the nearest RenderRepaintBoundary and calls toImage().
  final finders = <Finder>[find.byType(MaterialApp), find.byType(WidgetsApp)];

  for (final finder in finders) {
    if (finder.evaluate().isEmpty) continue;
    try {
      final Element element = finder.evaluate().first;
      final ui.Image image = await captureImage(element);
      final ByteData? byteData = await image.toByteData(
        format: ui.ImageByteFormat.png,
      );
      image.dispose();
      if (byteData != null && byteData.lengthInBytes > 0) {
        return byteData.buffer.asUint8List();
      }
    } catch (_) {
      continue;
    }
  }

  return null;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

Future<void> _ensureReportDir() async {
  if (_reportDir != null) return;
  _reportDir = Directory(
    p.join(await _reportRootPath(), 'build', 'e2e_report'),
  );
  _screenshotsDir = Directory(p.join(_reportDir!.path, 'screenshots'));
  await _screenshotsDir!.create(recursive: true);
  if (kDebugMode) {
    debugPrint('[E2E Report] Output directory: ${_reportDir!.path}');
  }
  await _loadManifest();
}

/// Root the report tree is written under.
///
/// On desktop the test process runs from the Flutter project directory, so
/// `build/e2e_report` lands next to the other build artifacts. On Android the
/// process runs inside the app sandbox where `Directory.current` is `/` and
/// not writable, so the report goes to the app's own external files directory
/// instead — a location `adb pull` can fetch after the run (see
/// `scripts/capture_screenshots.*`).
Future<String> _reportRootPath() async {
  if (!Platform.isAndroid) return Directory.current.path;

  // Ask the platform for the app's external files directory. This has to go
  // through the pre-sandbox provider: the sandbox redirects every path_provider
  // call into a throwaway temp dir the host cannot reach. Going through the
  // plugin also matters because `Android/data/<package>/files` is created by
  // the framework — a fresh install leaves it absent, and the app cannot mkdir
  // it itself under scoped storage.
  try {
    final external = await E2ESandboxPaths.platformProvider
        .getExternalStoragePath();
    if (external != null && external.isNotEmpty) {
      final root = Directory(p.join(external, 'cb_e2e'));
      root.createSync(recursive: true);
      return root.path;
    }
  } catch (_) {
    // Fall through to the fixed candidates below.
  }

  for (final base in kAndroidReportRoots) {
    try {
      Directory(base).createSync(recursive: true);
      return base;
    } catch (_) {
      // Try the next candidate.
    }
  }

  return Directory.current.path;
}

/// Fallback on-device roots for the Android report tree, most preferred first.
/// Only used when the platform cannot report an external files directory.
const List<String> kAndroidReportRoots = <String>[
  '/sdcard/Android/data/com.cbv.filehub/files/cb_e2e',
  '/storage/emulated/0/Android/data/com.cbv.filehub/files/cb_e2e',
  '/sdcard/Download/cb_e2e',
];

// ---------------------------------------------------------------------------
// Manifest — persists screenshot log + test results across process runs so
// reruns of a subset of tests don't wipe earlier results from the dashboard.
// ---------------------------------------------------------------------------

File? get _manifestFile =>
    _reportDir == null ? null : File(p.join(_reportDir!.path, 'manifest.json'));

Future<void> _loadManifest() async {
  if (_manifestLoaded) return;
  _manifestLoaded = true;
  final f = _manifestFile;
  if (f == null || !await f.exists()) return;
  try {
    final content = await f.readAsString();
    if (content.trim().isEmpty) return;
    final decoded = jsonDecode(content);
    if (decoded is! Map) return;

    final entries = decoded['entries'];
    if (entries is List) {
      for (final e in entries) {
        if (e is! Map) continue;
        final tn = e['testName'] as String?;
        final step = e['step'] as String?;
        final fname = e['filename'] as String?;
        final ts = e['ts'] as String?;
        if (tn == null || step == null || fname == null) continue;
        _log.add(
          _Entry(
            testName: tn,
            step: step,
            filename: fname,
            ts: ts != null
                ? (DateTime.tryParse(ts) ?? DateTime.now())
                : DateTime.now(),
          ),
        );
      }
    }

    final results = decoded['results'];
    if (results is Map) {
      for (final entry in results.entries) {
        final key = entry.key;
        final val = entry.value;
        if (key is String && val is bool) _testResults[key] = val;
      }
    }

    final counter = decoded['counter'];
    if (counter is int && counter > _counter) _counter = counter;

    if (kDebugMode) {
      debugPrint(
        '[E2E Report] Manifest loaded: ${_log.length} screenshot(s), '
        '${_testResults.length} test result(s)',
      );
    }
  } catch (_) {}
}

Future<void> _saveManifest() async {
  final f = _manifestFile;
  if (f == null) return;
  try {
    final entries = _log
        .map(
          (e) => {
            'testName': e.testName,
            'step': e.step,
            'filename': e.filename,
            'ts': e.ts.toIso8601String(),
          },
        )
        .toList();
    final body = {
      'entries': entries,
      'results': _testResults,
      'counter': _counter,
      'updatedAt': DateTime.now().toIso8601String(),
    };
    await f.writeAsString(jsonEncode(body));
  } catch (_) {}
}

/// Removes all entries for [testName] from the in-memory log and deletes the
/// on-disk screenshot files. Called on the first `init()` for a test in this
/// process so reruns produce clean output without losing other tests' results.
///
/// Idempotent within a single process — subsequent calls for the same test
/// (e.g. from manual `screenshot()` calls) are no-ops so we don't wipe
/// in-progress captures.
Future<void> _clearTestEntries(String testName) async {
  if (_clearedThisRun.contains(testName)) return;
  _clearedThisRun.add(testName);

  final stale = _log.where((e) => e.testName == testName).toList();
  if (stale.isEmpty) return;

  _log.removeWhere((e) => e.testName == testName);

  if (_screenshotsDir == null) return;
  for (final e in stale) {
    try {
      final file = File(p.join(_screenshotsDir!.path, e.filename));
      if (await file.exists()) await file.delete();
    } catch (_) {}
  }

  if (kDebugMode) {
    debugPrint(
      '[E2E Report] Cleared ${stale.length} stale screenshot(s) for "$testName"',
    );
  }
}

String _slugify(String s) => s
    .toLowerCase()
    .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
    .replaceAll(RegExp(r'^_+|_+$'), '');

String _esc(String s) => s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
