/// CoolBird colour tokens.
///
/// These are authored by hand rather than derived from
/// [ColorScheme.fromSeed]. Material's tonal-palette algorithm decides hue
/// rotation, chroma clamping and contrast for you, which is exactly the part
/// of the look we want to own — so the ramps below are literal values and the
/// accent ramp is generated by [CbAccentRamp] using rules we control.
///
/// Naming follows a two-layer convention:
///   * `CbNeutral` / `CbAccentRamp` are the *primitive* layer — raw ramps with
///     no meaning attached.
///   * [CbColorTokens] is the *semantic* layer — `surface`, `textPrimary`,
///     `stroke`… Widgets should only ever read the semantic layer, so a ramp
///     can be retuned without touching call sites.
library cb_color_tokens;

import 'dart:math' as math;
import 'dart:ui' show Brightness;

import 'package:flutter/painting.dart';

/// Cool-tinted neutral ramp.
///
/// A pure grey ramp reads as flat and slightly dirty against the accent
/// colours; every step here carries a small amount of blue (hue ≈ 220) so the
/// greys stay coherent with the accents and with the Windows desktop backdrop.
class CbNeutral {
  const CbNeutral._();

  static const Color n0 = Color(0xFFFFFFFF);
  static const Color n25 = Color(0xFFFCFCFD);
  static const Color n50 = Color(0xFFF8F9FB);
  static const Color n100 = Color(0xFFF1F3F7);
  static const Color n150 = Color(0xFFE8EBF1);
  static const Color n200 = Color(0xFFDDE1EA);
  static const Color n300 = Color(0xFFC6CCD9);
  static const Color n400 = Color(0xFF9BA3B4);
  static const Color n500 = Color(0xFF737B8C);
  static const Color n600 = Color(0xFF565D6D);
  static const Color n700 = Color(0xFF3E4450);
  static const Color n800 = Color(0xFF2A2E38);
  static const Color n850 = Color(0xFF20242C);
  static const Color n900 = Color(0xFF191C22);
  static const Color n950 = Color(0xFF121419);
  static const Color n1000 = Color(0xFF0B0D10);
}

/// A generated ramp of tints and shades around one accent colour.
///
/// The generation rules are deliberately simple and predictable: lightness is
/// driven to fixed targets while saturation is eased off at the pale end (so
/// tints do not turn neon) and held near the base at the dark end (so shades
/// do not turn muddy). This is the piece that replaces `ColorScheme.fromSeed`.
class CbAccentRamp {
  /// Palest tint — hover/selection washes.
  final Color tint;

  /// Slightly stronger wash — pressed states on subtle surfaces.
  final Color tintStrong;

  /// Border/outline weight of the accent.
  final Color border;

  /// The accent proper. Fills, active indicators, focus rings.
  final Color base;

  /// Hover state for filled accent surfaces.
  final Color hover;

  /// Pressed state for filled accent surfaces.
  final Color pressed;

  /// Text/icon colour when drawn *on* [base].
  final Color onBase;

  /// Accent tuned for use as text or icons on a neutral surface, where [base]
  /// often lacks contrast.
  final Color text;

  const CbAccentRamp({
    required this.tint,
    required this.tintStrong,
    required this.border,
    required this.base,
    required this.hover,
    required this.pressed,
    required this.onBase,
    required this.text,
  });

  /// Builds a ramp from a single accent colour for the given [brightness].
  factory CbAccentRamp.from(Color accent, Brightness brightness) {
    final hsl = HSLColor.fromColor(accent);
    final bool isDark = brightness == Brightness.dark;

    // In dark mode the accent sits on a near-black surface, so it is lifted
    // and slightly desaturated; a fully saturated accent vibrates against
    // dark neutrals.
    final HSLColor core = isDark
        ? hsl
            .withLightness(_clamp(hsl.lightness + 0.10))
            .withSaturation(_clamp(hsl.saturation * 0.88))
        : hsl;

    Color at(double lightness, double saturationScale) => core
        .withLightness(_clamp(lightness))
        .withSaturation(_clamp(core.saturation * saturationScale))
        .toColor();

    if (isDark) {
      return CbAccentRamp(
        tint: core.withLightness(0.16).withSaturation(0.42).toColor(),
        tintStrong: core.withLightness(0.22).withSaturation(0.48).toColor(),
        border: at(0.34, 0.70),
        base: core.toColor(),
        hover: at(core.lightness + 0.07, 1.0),
        pressed: at(core.lightness - 0.06, 0.94),
        onBase: _readableOn(core.toColor()),
        text: _textOn(core, CbNeutral.n950, lighten: true),
      );
    }

    return CbAccentRamp(
      tint: core.withLightness(0.96).withSaturation(0.72).toColor(),
      tintStrong: core.withLightness(0.91).withSaturation(0.76).toColor(),
      border: at(0.78, 0.80),
      base: core.toColor(),
      hover: at(core.lightness - 0.06, 1.0),
      pressed: at(core.lightness - 0.12, 1.0),
      onBase: _readableOn(core.toColor()),
      text: _textOn(core, CbNeutral.n0, lighten: false),
    );
  }

  static double _clamp(double v) => v.clamp(0.0, 1.0);

  /// Picks the ink colour — near-white or near-black — that contrasts better
  /// with [background].
  ///
  /// The accent set spans very dark (green `#107C10`) to very light
  /// (yellow `#F9C80E`), so a fixed choice fails at one end or the other.
  static Color _readableOn(Color background) {
    return _contrastRatio(CbNeutral.n0, background) >=
            _contrastRatio(CbNeutral.n1000, background)
        ? CbNeutral.n0
        : CbNeutral.n1000;
  }

  /// Walks the accent's lightness until it clears WCAG AA (4.5:1) against
  /// [surface].
  ///
  /// Deriving this by measurement rather than by a lightness rule of thumb
  /// matters because contrast does not track lightness evenly across hues: a
  /// mid-lightness teal and a mid-lightness blue sit on opposite sides of the
  /// threshold. Stepping in small increments keeps the result as close to the
  /// chosen accent as legibility allows.
  static Color _textOn(HSLColor accent, Color surface,
      {required bool lighten}) {
    const double target = 4.5;
    const double step = 0.02;

    HSLColor candidate = accent;
    for (int i = 0; i < 50; i++) {
      final color = candidate.toColor();
      if (_contrastRatio(color, surface) >= target) return color;

      final double next =
          lighten ? candidate.lightness + step : candidate.lightness - step;
      if (next <= 0.0 || next >= 1.0) break;
      candidate = candidate.withLightness(next);
    }
    // Ran out of headroom — fall back to plain text rather than an
    // illegible accent.
    return lighten ? CbNeutral.n50 : CbNeutral.n900;
  }

  static double _contrastRatio(Color a, Color b) {
    final la = _relativeLuminance(a);
    final lb = _relativeLuminance(b);
    final lighter = math.max(la, lb);
    final darker = math.min(la, lb);
    return (lighter + 0.05) / (darker + 0.05);
  }

  static double _relativeLuminance(Color color) {
    double channel(double value) => value <= 0.03928
        ? value / 12.92
        : math.pow((value + 0.055) / 1.055, 2.4).toDouble();
    return 0.2126 * channel(color.r) +
        0.7152 * channel(color.g) +
        0.0722 * channel(color.b);
  }
}

/// Status hues, independent of the user's accent choice.
///
/// These never change with the accent picker — a destructive action must read
/// as destructive whether the user picked red or green as their accent.
class CbStatusPalette {
  final Color success;
  final Color successSurface;
  final Color warning;
  final Color warningSurface;
  final Color danger;
  final Color dangerHover;
  final Color dangerSurface;
  final Color info;
  final Color infoSurface;

  const CbStatusPalette({
    required this.success,
    required this.successSurface,
    required this.warning,
    required this.warningSurface,
    required this.danger,
    required this.dangerHover,
    required this.dangerSurface,
    required this.info,
    required this.infoSurface,
  });

  static const CbStatusPalette light = CbStatusPalette(
    success: Color(0xFF117A43),
    successSurface: Color(0xFFECF8F1),
    warning: Color(0xFF9A6206),
    warningSurface: Color(0xFFFDF4E4),
    danger: Color(0xFFC02B33),
    dangerHover: Color(0xFFA5232A),
    dangerSurface: Color(0xFFFDEFEF),
    info: Color(0xFF1F5FA8),
    infoSurface: Color(0xFFEDF3FC),
  );

  static const CbStatusPalette dark = CbStatusPalette(
    success: Color(0xFF48C78A),
    successSurface: Color(0xFF16281F),
    warning: Color(0xFFE0A33A),
    warningSurface: Color(0xFF2A2214),
    danger: Color(0xFFF06A70),
    dangerHover: Color(0xFFF58489),
    dangerSurface: Color(0xFF2C1A1C),
    info: Color(0xFF6BA6EE),
    infoSurface: Color(0xFF16202C),
  );

  static CbStatusPalette of(Brightness brightness) =>
      brightness == Brightness.dark ? dark : light;
}

/// The semantic colour layer — the only colour API widgets should touch.
class CbColorTokens {
  // Surfaces, ordered back-to-front.
  /// The window/page background, furthest back.
  final Color canvas;

  /// Default panel surface sitting on [canvas].
  final Color surface;

  /// Raised surface — cards, list rows, inline containers.
  final Color surfaceRaised;

  /// Floating surface — menus, popovers, dialogs, toasts.
  final Color surfaceOverlay;

  /// Recessed surface — input fields, wells, code blocks.
  final Color surfaceSunken;

  /// Hover wash applied over any surface.
  final Color surfaceHover;

  /// Pressed wash applied over any surface.
  final Color surfacePressed;

  /// Selected-row background.
  final Color surfaceSelected;

  // Content.
  final Color textPrimary;
  final Color textSecondary;
  final Color textTertiary;
  final Color textDisabled;
  final Color textInverse;
  final Color icon;
  final Color iconSubtle;

  // Lines.
  final Color stroke;
  final Color strokeSubtle;
  final Color strokeStrong;
  final Color focusRing;

  // Depth.
  final Color shadow;
  final Color scrim;

  final CbAccentRamp accent;
  final CbStatusPalette status;

  const CbColorTokens({
    required this.canvas,
    required this.surface,
    required this.surfaceRaised,
    required this.surfaceOverlay,
    required this.surfaceSunken,
    required this.surfaceHover,
    required this.surfacePressed,
    required this.surfaceSelected,
    required this.textPrimary,
    required this.textSecondary,
    required this.textTertiary,
    required this.textDisabled,
    required this.textInverse,
    required this.icon,
    required this.iconSubtle,
    required this.stroke,
    required this.strokeSubtle,
    required this.strokeStrong,
    required this.focusRing,
    required this.shadow,
    required this.scrim,
    required this.accent,
    required this.status,
  });

  /// Builds the semantic set for [brightness] around the user's [accent].
  factory CbColorTokens.of(Brightness brightness, Color accent) {
    final ramp = CbAccentRamp.from(accent, brightness);
    final status = CbStatusPalette.of(brightness);

    if (brightness == Brightness.dark) {
      return CbColorTokens(
        canvas: CbNeutral.n1000,
        surface: CbNeutral.n950,
        surfaceRaised: CbNeutral.n900,
        surfaceOverlay: CbNeutral.n850,
        surfaceSunken: CbNeutral.n1000,
        surfaceHover: const Color(0x0FFFFFFF),
        surfacePressed: const Color(0x1AFFFFFF),
        surfaceSelected: ramp.tint,
        textPrimary: const Color(0xFFF2F4F8),
        textSecondary: const Color(0xFFAAB2C0),
        textTertiary: const Color(0xFF7C8494),
        textDisabled: const Color(0xFF565D6D),
        textInverse: CbNeutral.n1000,
        icon: const Color(0xFFC8CEDA),
        iconSubtle: const Color(0xFF8C94A3),
        stroke: const Color(0x1FFFFFFF),
        strokeSubtle: const Color(0x14FFFFFF),
        strokeStrong: const Color(0x38FFFFFF),
        focusRing: ramp.text,
        shadow: const Color(0xFF000000),
        scrim: const Color(0x99000000),
        accent: ramp,
        status: status,
      );
    }

    return CbColorTokens(
      canvas: CbNeutral.n50,
      surface: CbNeutral.n0,
      surfaceRaised: CbNeutral.n0,
      surfaceOverlay: CbNeutral.n0,
      surfaceSunken: CbNeutral.n100,
      surfaceHover: const Color(0x0A0B0D10),
      surfacePressed: const Color(0x140B0D10),
      surfaceSelected: ramp.tint,
      textPrimary: CbNeutral.n900,
      textSecondary: CbNeutral.n600,
      textTertiary: CbNeutral.n500,
      textDisabled: CbNeutral.n400,
      textInverse: CbNeutral.n0,
      icon: CbNeutral.n600,
      iconSubtle: CbNeutral.n500,
      stroke: const Color(0x1F0B0D10),
      strokeSubtle: const Color(0x120B0D10),
      strokeStrong: const Color(0x330B0D10),
      focusRing: ramp.base,
      shadow: const Color(0xFF0B0D10),
      scrim: const Color(0x66000000),
      accent: ramp,
      status: status,
    );
  }

  CbColorTokens copyWith({
    Color? canvas,
    Color? surface,
    Color? surfaceRaised,
    Color? surfaceOverlay,
    Color? surfaceSunken,
    Color? surfaceHover,
    Color? surfacePressed,
    Color? surfaceSelected,
    Color? textPrimary,
    Color? textSecondary,
    Color? textTertiary,
    Color? textDisabled,
    Color? textInverse,
    Color? icon,
    Color? iconSubtle,
    Color? stroke,
    Color? strokeSubtle,
    Color? strokeStrong,
    Color? focusRing,
    Color? shadow,
    Color? scrim,
    CbAccentRamp? accent,
    CbStatusPalette? status,
  }) {
    return CbColorTokens(
      canvas: canvas ?? this.canvas,
      surface: surface ?? this.surface,
      surfaceRaised: surfaceRaised ?? this.surfaceRaised,
      surfaceOverlay: surfaceOverlay ?? this.surfaceOverlay,
      surfaceSunken: surfaceSunken ?? this.surfaceSunken,
      surfaceHover: surfaceHover ?? this.surfaceHover,
      surfacePressed: surfacePressed ?? this.surfacePressed,
      surfaceSelected: surfaceSelected ?? this.surfaceSelected,
      textPrimary: textPrimary ?? this.textPrimary,
      textSecondary: textSecondary ?? this.textSecondary,
      textTertiary: textTertiary ?? this.textTertiary,
      textDisabled: textDisabled ?? this.textDisabled,
      textInverse: textInverse ?? this.textInverse,
      icon: icon ?? this.icon,
      iconSubtle: iconSubtle ?? this.iconSubtle,
      stroke: stroke ?? this.stroke,
      strokeSubtle: strokeSubtle ?? this.strokeSubtle,
      strokeStrong: strokeStrong ?? this.strokeStrong,
      focusRing: focusRing ?? this.focusRing,
      shadow: shadow ?? this.shadow,
      scrim: scrim ?? this.scrim,
      accent: accent ?? this.accent,
      status: status ?? this.status,
    );
  }
}
